### ISSUE TITLE
:'( ughhhhh Need a way of doing custom content replacements for edx

### ISSUE THREAD

**Issue by cycomachead** [beautyjoy/llab-to-edx#30]
Probably just need some YALM file so we can track stuff

``` yaml

- path: something.html
  replacements:
     - from: "string<of>stuff"
       to: this is edx specific content
    - from: ...
      to: ...
```
