### ISSUE TITLE
LKJNLFBNSFGJNPAFGEI[RGEVMWOEIRNV[OEIRG[OB CSS ERGNPEORFNPOQERNGPOQEGNROQPGN

### ISSUE THREAD

**Issue by cycomachead** [beautyjoy/llab-to-edx#31]
Edx bootstrap customization classes...

We need to add in custom CSS stuff. GAH. Life. Is. Annoying.

``` css
.llab-full .alert {
    min-width: none;
    max-width: none;
}
```
